### ISSUE TITLE
Terminal getText not working correctly

### ISSUE THREAD

**Issue by degrammer** [webdriverio-community/wdio-vscode-service#69]
The `getText` method from `TerminalView` is not working correctly.
It selects the Terminal output executing the [wrong copy command](https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/pageobjects/bottomBar/Views.ts#L192): **terminal copy selection**
There is no such command.
One alternative could be to modify the command to use **copy**

Reproduction example:

```
 const workbench = await browser.getWorkbench()
 const bottomBar = workbench.getBottomBar()
 const terminalView = await bottomBar.openTerminalView()
 const text = await terminalView.getText() // returns empty value
```

A temporary workaround:

```
 import clipboard from 'clipboardy'

 const workbench = await browser.getWorkbench()
 await workbench.executeCommand('Terminal select all')
 await workbench.executeCommand('Copy')

// Use the clipboard to get the copied text.
  const text = await clipboard.read()
  await clipboard.write('')
```

**Comment by christian-bromann** [comment]
Hey @degrammer 

thanks for raising the issue.

I added a test for this in https://github.com/webdriverio-community/wdio-vscode-service/commit/3050417daeb14a61a9079095e2614369ebafb158. It seems that the way `getText` was implemented wasn't working anymore since the command for copying the text from the terminal was removed in VS Code. This is now fixed.
